version: '3.1'

volumes:
  mongodbdata:
    external: false

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - 'mongodbdata:/data'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    command: mongod --smallfiles --logpath=/dev/null

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: lol
      ME_CONFIG_BASICAUTH_PASSWORD: lol
    depends_on:
      - mongo